// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.DAL;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410114033_AddProductTable")]
    partial class AddProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_end.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Доставка",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доставка груза в течение 24 часов по всей стране",
                            ImageUrl = "https://placehold.co/400x400?text=Express",
                            IsActive = true,
                            Name = "Экспресс-доставка",
                            Price = 49.99m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 2,
                            Category = "Доставка",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доставка груза в течение 3-5 рабочих дней",
                            ImageUrl = "https://placehold.co/400x400?text=Standard",
                            IsActive = true,
                            Name = "Стандартная доставка",
                            Price = 19.99m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 3,
                            Category = "Грузоперевозки",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Перевозка крупногабаритных и тяжёлых грузов",
                            ImageUrl = "https://placehold.co/400x400?text=Heavy",
                            IsActive = true,
                            Name = "Доставка негабарита",
                            Price = 199.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = "Международная",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доставка грузов в 48 штатов США",
                            ImageUrl = "https://placehold.co/400x400?text=International",
                            IsActive = true,
                            Name = "Международная доставка",
                            Price = 299.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "Спецперевозка",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Бережная перевозка хрупких и ценных грузов",
                            ImageUrl = "https://placehold.co/400x400?text=Fragile",
                            IsActive = true,
                            Name = "Хрупкий груз",
                            Price = 79.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Доставка",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доставка груза с ночным временным слотом",
                            ImageUrl = "https://placehold.co/400x400?text=Night",
                            IsActive = false,
                            Name = "Ночная доставка",
                            Price = 89.99m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("back_end.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
