// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.DAL;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_end.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("back_end.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Oversized Containers",
                            ImageUrl = "/images/real9.jpg",
                            IsActive = true,
                            Name = "Colorado Springs → Tampa",
                            Price = 4100m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / HVAC Units",
                            ImageUrl = "/images/real2.jpg",
                            IsActive = true,
                            Name = "Madera → Fort Collins",
                            Price = 5120m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Steel Beams",
                            ImageUrl = "/images/real3.jpg",
                            IsActive = true,
                            Name = "Deer Park → Jackson",
                            Price = 2100m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Partial",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stepdeck / Heavy Machinery",
                            ImageUrl = "/images/real4.jpg",
                            IsActive = true,
                            Name = "Salt Lake City → Houston",
                            Price = 5500m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Equipment",
                            ImageUrl = "/images/real5.jpg",
                            IsActive = true,
                            Name = "Key Largo → Lake Ozark",
                            Price = 4000m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Military Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Military / Multi-Stop",
                            ImageUrl = "/images/real6.jpg",
                            IsActive = true,
                            Name = "Anniston → Apache Junction",
                            Price = 19499m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Heavy Equipment",
                            ImageUrl = "/images/real7.jpg",
                            IsActive = true,
                            Name = "Connellsville → Snyder",
                            Price = 3100m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Partial",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Construction Equipment",
                            ImageUrl = "/images/real8.jpg",
                            IsActive = true,
                            Name = "Las Vegas → Carnesville",
                            Price = 6350m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Multi-Stop Steel",
                            ImageUrl = "/images/real1.jpg",
                            IsActive = true,
                            Name = "Houston → Jackson",
                            Price = 14900m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "Full Load",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flatbed / Heavy Equipment",
                            ImageUrl = "/images/real10.jpg",
                            IsActive = true,
                            Name = "Phoenix → Memphis",
                            Price = 6800m,
                            Stock = 1
                        });
                });

            modelBuilder.Entity("back_end.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("back_end.Domain.Order", b =>
                {
                    b.HasOne("back_end.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
